<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20180510131116 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription()
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('ALTER TABLE miweb_community_domain_model_user ADD icon VARCHAR(40) DEFAULT NULL');
        $this->addSql('ALTER TABLE miweb_community_domain_model_user ADD CONSTRAINT FK_7C8519A2659429DB FOREIGN KEY (icon) REFERENCES neos_media_domain_model_image (persistence_object_identifier)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7C8519A2659429DB ON miweb_community_domain_model_user (icon)');
        $this->addSql('ALTER TABLE neos_media_domain_model_asset CHANGE assetsourceidentifier assetsourceidentifier VARCHAR(255) NOT NULL');
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('ALTER TABLE miweb_community_domain_model_user DROP FOREIGN KEY FK_7C8519A2659429DB');
        $this->addSql('DROP INDEX UNIQ_7C8519A2659429DB ON miweb_community_domain_model_user');
        $this->addSql('ALTER TABLE miweb_community_domain_model_user DROP icon');
        $this->addSql('ALTER TABLE neos_media_domain_model_asset CHANGE assetsourceidentifier assetsourceidentifier VARCHAR(255) DEFAULT \'neos\' COLLATE utf8mb4_unicode_ci');
    }
}